[theme]
primaryColor = "#E23744"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a0a0a"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
